version: '3.8'

services:
  nginx:
    build: ./srcs/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/vsozonof/data/nginx:/etc/nginx
      - /home/vsozonof/data/nginx/html:/var/www/wordpress
      - ./srcs/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./srcs/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./srcs/nginx/conf/nginx.sh:/nginx.sh
      - /etc/nginx/ssl/inception.crt:/etc/nginx/ssl/inception.crt
      - /etc/nginx/ssl/inception.key:/etc/nginx/ssl/inception.key
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build: ./srcs/wordpress
    container_name: wordpress
    environment:
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_EMAIL: ${WP_EMAIL}
      WP_USER2: ${WP_USER2}
      WP_PASSWORD2: ${WP_PASSWORD2}
      WP_EMAIL2: ${WP_EMAIL2}
    volumes:
      - /home/vsozonof/data/wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    expose:
      - "9000"
    ports:
      - "9000:9000"

  mariadb:
    build: ./srcs/mariadb
    container_name: mariadb
    environment:
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
    networks:
      - inception
    volumes:
      - /home/vsozonof/data/mariadb:/var/lib/mysql

networks:
  inception:
    driver: bridge

